### ISSUE TITLE
Explosion caused by spells shot from your left arm would damage yourself.

### ISSUE THREAD

**Issue by XM666-Dev** [DrChaleceCume/Twin-Linked#1]
In the left_arm.xml:
Please add`<LuaComponent script_shot="mods/Twin-Linked/files/scripts/shot.lua"></LuaComponent>`
In the shot.lua:
Please add
![屏幕截图 2023-10-03 145229](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/2a638340-8f43-4dc8-be47-d3b8c4a8bf4b)
So, you can fix this bug.

**Comment by re-coilless** [comment]
Thanks! Though, fuck, makes me realize how old this mod truly is if I wasn't even aware of mWhoShot at the time. I'll fix it within this github then but won't update the steam version for the time being - will push Twin-Linked right to the 2.0 closer to the end of this month.

**Comment by re-coilless** [comment]
Also, I never really pushed this mod to the lategame, so if you've encountered any strange edge cases (or perk incompatibilities, modded or not), a report would be highly appreciated.
