### ISSUE TITLE
Add extra condition check for shot_controller.lua

### ISSUE THREAD

**Issue by XM666-Dev** [DrChaleceCume/Twin-Linked#2]
I still find some strange friendly fire bugs when I use mod spells, which may be caused by this mod?
The "script_shot" will also trigger when player shots (This means that shooting by the player themselves instead of their left arm will still trigger this script), so you should do like that.
![屏幕截图 2024-01-20 152721](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/54b49b55-573d-43f8-a40e-429a6d086a48)
Sorry for bad English.

**Comment by re-coilless** [comment]
Done. Also, how's the HermeS Index itself, do you have any immediate feedback or feature requests?

**Comment by XM666-Dev** [comment]
What is HermeS Index?

**Comment by re-coilless** [comment]
Oh, since the Twin-Linked 2.0 wouldn't work without it, I assumed you have it installed already. But the new version shouldn't even launch of no Index is present?

Anyways, HermeS Index is an inventory framework in a form of a complete vanilla GUI rewrite. It has some dependencies of its own, so if you'd like to install it, here the "modpack" you'll require (presented in load order):
- https://github.com/DrChaleceCume/penman
- https://github.com/DrChaleceCume/mnee
- https://github.com/DrChaleceCume/Twin-Linked
- https://github.com/DrChaleceCume/index_core

**Comment by XM666-Dev** [comment]
Sorry I haven ‘t notice that, I'm still play with old version of Twin-Linked.
After trying, I have surprised by this great GUI framework.
This great mod rewrites vanilla GUI. I have made a mod named "noita inventory" before, makes player can place potions into spell inventory, and place spells into potion inventory.
I want to make more features, but it's difficult to check vanilla inventory inputs. Then I thought about rewriting the vanilla GUI, also provide support for your Twin-Linked mod, but in the end, I gave up this idea.
And now your great mod is here. So, I could continue developing the "noita inventory" mod. Has the HermeS Index provides an API, to get GUI inputs?
I need to get the inventory item dragging info.

**Comment by XM666-Dev** [comment]
Mm... I can't use shift + click to quick move inventory spell. Is it will add later?
And there are some visual bugs.
The spell names are disappeared when I use Chinese language. (Also perk names)
![屏幕截图 2024-01-23 130620](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/867a4946-9ed3-4384-b5a3-5dbad186b399)
GUIs are disappeared when mouse cursor is targeting at some mod spells. Also, can't move them. (This spell is from [“剑仙技能组”](https://steamcommunity.com/sharedfiles/filedetails/?id=3058541733) mod in steam workshop)
![屏幕截图 2024-01-23 130544](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/71675fce-1d76-4c65-b34e-44f3877dd247)
And it doesn't support multi rows of inventory. See the [Adjustable Inventory Size](https://steamcommunity.com/sharedfiles/filedetails/?id=2336685059&searchtext=Adjustable+Inventory+Size) mod. 
![屏幕截图 2024-01-23 130658](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/e55fce47-fe6c-445f-9e9c-5f54df2676d8)
![屏幕截图 2024-01-23 130735](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/b6bf5096-cf49-469d-a2bb-74094bf536b6)
Secondary key binds don't work.
![屏幕截图 2024-01-23 134436](https://github.com/DrChaleceCume/Twin-Linked/assets/99076011/eb7938a1-5316-480a-bdc5-56557191db72)

**Comment by re-coilless** [comment]
Alright, let's see.
- The proper inventory API is the main purpose of this mod, as I am intending to use it for fully custom inventory projects of my own. At the moment, there's no documentation though and the inner structure is a subject to change, so I'd advice waiting for a little while before basing something on this framework. (If you'd like to anyways, I can provide directions on where and how to hook in.)
- The shift-click is WIP right now, yes.
- The non-existent support of the Chinese language is a problem of how vanilla handles Asian languages in general. There is a fix to this but it will require some time to implement legitimately.
- The spells crashing the GUI can happen if something odd occurs but I believe the better coding practice would be to add an actual check. Will fix.
- Index does actually support multi-row inventories, so there must be something strange going on between two mods. I'll look into it.
- The vanilla key binds are inaccessible from within the modding API sadly - to rebind anything you will have to press CTRL+M and navigate the menu that will appear.

Also, we'd better move to the Index's Issues section, I'll open all the stuff you reported and feel free to add more as you discover them.
